---
## python3 –m pip install ansible-navigator
## ansible-builder build -t custom-ee -v3
## ansible-navigator run playbook.yml -i inventory/ --eei custom-ee –-pull-policy missing –-mode stdout
version: 3
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: zabbix.zabbix
        version: '>=1.3.3'
      - name: ansible.utils
        version: '>=2.8.0'
      - name: ansible.posix
        version: '>=1.4.0'
      - name: ansible.netcommon
        version: '>=3.1.1'
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
    python:
      - netaddr>=0.8
      - Jinja2==3.1.2
  system:
    - openssl

images:
    name: quay.io/centos/centos:stream9
