---
- name: Webhook test
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: '{{ webhook_port | default(5001) }}'
  rules:
    - name: Run playbook
      condition: >-
        event.payload is defined
        event.payload.playbook is defined
        and event.payload.playbook
      action:
        run_playbook:
          name: playbook1.yml
    - name: Print event
      condition: event.payload is defined
      action:
        print_event:
          pretty: true
