---
- name: Webhook test
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: '{{ webhook_port | default(5001) }}'
  rules:
    - name: debug
      condition: event.payload is defined
      action:
        debug:
